version: "3.3"

services:
  elasticsearch:
    build: ./elasticsearch/
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - "TZ=Asia/Tokyo"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "TZ=Asia/Tokyo"
      - I18N_LOCALE="ja-JP"
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - esnet

volumes:
  es-data:
    driver: local

networks:
  esnet:
